default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode

development:
  <<: *default
  database: debtify_development
  pool:     5
  username: debtify
  password:
  template: template0

test:
  <<: *default
  database: debtify_test
  pool:     5
  username: debtify
  password:
  template: template0

production:
  <<: *default
  host: <%= ENV["DEBTIFY_DBHOST"] %>
  database: <%= ENV["DEBTIFY_DBNAME"] %>
  pool:     10
  username: <%= ENV["DEBTIFY_DBUSER"] %>
  password: <%= ENV["DEBTIFY_DBPASSWORD"] %>
  template: template0

